/**
 * Write a description of class weather_divisible_by_3and5_or_not here.
 *
 * @author (1337 mickey)
 * @version (a version number or a date)
 */
public class weather_divisible_by_3and5_or_not
{
    public static void main(String[] args){
        
        int number;
        number = 35;
        
            if(number% 3==0 && number% 5==0){
                System.out.println("divisible");
            
            }
            else{
            
                System.out.println("not divisible");
            }
            
    }
